# syntax=docker/dockerfile:1
FROM python:3.11
RUN apt-get update && apt-get -y install cron
WORKDIR /app
COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD CMD ["py", "app.py" ]
