version: '3'


volumes:
  postgres_data:
  redis_data:
  files_path:

services:
  
  
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data/redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: appnube
      POSTGRES_PASSWORD: convertir
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copia el script sql para crear las tablas
      - ./migrations/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    ports:
      - "5432:5432"

  celery_worker:
    build: ./worker
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:convertir@54.226.135.40:5432/appnube
      REDIS_URL: redis://54.226.135.40:6379/0
   
    command: celery -A tasks worker --loglevel=info    
    volumes:
      - files_path:/data/files  

  python_api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:convertir@54.226.135.40:5432/appnube
      REDIS_URL: redis://54.226.135.40:6379/0
    depends_on:
      - celery_worker
    ports:
      - "8000:8000"
    volumes:
      - files_path:/data/files 


